- name: install build depends for Ruby
  yum: name={{ item }} state=present
  with_items:
    - gcc
    - openssl-devel
    - libyaml-devel
    - readline-devel
    - zlib-devel
  sudo: true
  tags:
    - rbenv
    - ruby

- name: check ruby rbenv installed
  shell: ~/.rbenv/bin/rbenv versions | grep {{ ruby_version }} | tr '*' ' ' | sed -e 's/\s\+//' | cut -f1 -d' '
  register: ruby_installed
  ignore_errors: yes
  tags:
    - ruby

- name: rbenv install {{ ruby_version }}
  command: ~/.rbenv/bin/rbenv install {{ ruby_version }}
  when: ruby_installed.stdout.find('{{ ruby_version }}') != 0
  tags:
    - ruby

- name: rbenv global {{ ruby_version }}
  command: ~/.rbenv/bin/rbenv global {{ ruby_version }}
  when:  ruby_installed.stdout.find('{{ ruby_version }}') != 0
  tags:
    - rubyglobal
    - ruby
