- name: gem install bundler
  gem: name=bundler executable=~/.rbenv/shims/gem user_install=false
  tags: bundler

- name: yum install before bundle install
  yum: name={{ item }} state=installed
  with_items:
    - libxml2
    - libxml2-devel
    - libxslt
    - libxslt-devel
    - ImageMagick-devel
  sudo: true
  tags: bundler
 
- name: bundle install
  command: ~/.rbenv/shims/bundle install chdir={{ synced_folder }}
  tags: bundler
